### ISSUE TITLE
Programming Language

### ISSUE THREAD

**Issue by SebastiaanYN** [The-SourceCode/Open-SourceBot#1]
Let's discuss the language choice for the bot here. Some options would be:
- Java
- JavaScript
- Python
- Kotlin
- Golang
- C#
- Rust

Please comment which language you would prefer, and the library you would want to use.

**Comment by akaStannn** [comment]
JavaScript, DiscordJS

**Comment by MY5TERIO** [comment]
Java, JDA

**Comment by waspothegreat** [comment]
Javascript, Discordjs

**Comment by AlfiePerkins123** [comment]
Javascript, DJS

**Comment by Mas03** [comment]
Java - JDA. Why? I mostly use Java and JDA, any Java lib tbh is fine I don't really care I can learn. A large proportion of the community learn D.JS and that's what it;ll be mostly likely. But for those minority of us who do JDA could we maybe do a JDA branch? Please? :P Anyways my opinion on the matter.

**Comment by Anish-Shobith** [comment]
Javascript, Discord.js

**Comment by Mas03** [comment]
Also just saying but if its JS, Stan you can teach me.

**Comment by MY5TERIO** [comment]
Don't do JS, we will have more trouble in DBH and it will be hell even more do JDA

**Comment by Joonitoi** [comment]
Rust, cool and very usable language. Perfect for a discord bot

**Comment by SebastiaanYN** [comment]
> Java - JDA. Why? I mostly use Java and JDA, any Java lib tbh is fine I don't really care I can learn. A large proportion of the community learn D.JS and that's what it;ll be mostly likely. But for those minority of us who do JDA could we maybe do a JDA branch? Please? :P Anyways my opinion on the matter.

Doing 2 branches could create a mess. The bot would be split up into 2 different sections, which can create confusion. Using 2 different languages for the bot itself might also create some complicated scenarios. If someone wants to work on a command chances would be they can't because it's in the wrong language.

A possibility would be having some services written in different languages, but that's something to worry about later on.

**Comment by JustWesley** [comment]
JDA #random vote because i don't do bots

**Comment by SuperSt3ve** [comment]
JavaScript, Discord.JS/Node.JS

**Comment by SebastiaanYN** [comment]
> Don't do JS, we will have more trouble in DBH and it will be hell even more do JDA

These 2 things have nothing to do with eachother

**Comment by PhelixTaken** [comment]
Java JDA of course 👍

**Comment by Mas03** [comment]
> > Java - JDA. Why? I mostly use Java and JDA, any Java lib tbh is fine I don't really care I can learn. A large proportion of the community learn D.JS and that's what it;ll be mostly likely. But for those minority of us who do JDA could we maybe do a JDA branch? Please? :P Anyways my opinion on the matter.
> 
> Doing 2 branches could create a mess. The bot would be split up into 2 different sections, which can create confusion. Using 2 different languages for the bot itself might also create some complicated scenarios. If someone wants to work on a command chances would be they can't because it's in the wrong language.
> 
> A possibility would be having some services written in different languages, but that's something to worry about later on.

I mean it can causes issues correct, i mean just saying if it turns to JS you and stan can teach me? Thats the deal. :lol:

**Comment by AlfiePerkins123** [comment]
Ive changed my mind, i think Python would be good with Discord.py

**Comment by SebastiaanYN** [comment]
In all scenarios the project should contain strict guidelines. Having unit tests, a linter and code reviews. This will make it easier to enforce the same style and improve the quality of the project.

**Comment by akaStannn** [comment]
> Don't do JS, we will have more trouble in DBH and it will be hell even more do JDA

Please support your opinion, assuming it's nonsense. I already told you this in the server itself, and DBH isn't as big as a hell as you say it is, and no, it won't be worse.

**Comment by MY5TERIO** [comment]
Make a branch for each api listed

**Comment by Ricky12Awesome** [comment]
JavaCord. It's better than JDA (except it doesn't have voice support). also try something new.
it should be coded in kotlin ofc. But you can use both Java and Kotlin if you want. but not recommended.

**Comment by SuperSt3ve** [comment]
What bot though? You guys gonna make a new discord bot for TSC??? And a new tutorial? Or what..?

**Comment by SebastiaanYN** [comment]
> What bot though? You guys gonna make a new discord bot for TSC??? And a new tutorial? Or what..?

This will, probably, be a standalone bot. It's just going to be an open-source project so people can help develop it.

**Comment by SacredAI** [comment]
You could easily split the bot with different sections of the page a whole new bot in a different language that way even if people are dumb it would be a struggle to mess up it doesn't necessarily have to be different branches

**Comment by RavvenLord** [comment]
Goland. With an incredible startup time and great focus on sub routines , the language is great for a service. Wherever the bot is hosted, go is supported in CF and runs great in kubernetes. The language is also easy to learn as well as easy to install

**Comment by LynxPlay101** [comment]
Goland. With an incredible startup time and great focus on sub routines , the language is great for a service. Wherever the bot is hosted, go is supported in CF and runs great in kubernetes. The language is also easy to learn as well as easy to install

**Comment by devilowsky** [comment]
Jda

**Comment by acollierr17** [comment]
JavaScript, Discord.js. That's where my experience mainly lies in languages (at this time).

**Comment by WarHammer414** [comment]
JavaScript since it would probably be the one used considering the amount of users that know and use it.

**Comment by SacredAI** [comment]
DiscordJS: 7 Votes
JDA: 5
JavaCord: 1
Rust: 1
Python: 1
GoLand: 1
Current Votes.

**Comment by DarkSeraphim** [comment]
Golang, C# or Rust

**Comment by MrSheldon** [comment]
Java, JDA

**Comment by ramidzkh** [comment]
Multiple languages with [GraalVM](https://www.graalvm.org/)?

**Comment by SacredAI** [comment]
gross no

**Comment by TheForbiddenAi** [comment]
Please vote here https://www.strawpoll.me/17588003

**Comment by TheForbiddenAi** [comment]
The community has decided that we are doing discord.js
